services:
  - type: web
    name: server-hub
    runtime: node
    region: oregon
    plan: free
    healthCheckPath: /api/healthz
    buildCommand: cd backend && npm install && npm run build && cd ../frontend && npm install && npx vite build
    startCommand: cd backend && node --enable-source-maps dist/index.mjs
    envVars:
      - key: PORT
        value: 3001
      - key: NODE_ENV
        value: production
      - key: LANG
        value: en_US.UTF-8
      - key: LC_ALL
        value: en_US.UTF-8
