import { createContext, useContext, useState, useEffect, type ReactNode } from "react";

export type Lang = "en" | "ar";

const translations = {
  en: {
    dashboard: "Dashboard",
    terminal: "Terminal",
    editor: "Editor",
    files: "Files",
    ai_chat: "AI Chat",
    commands: "Commands",
    admin: "Admin Panel",
    settings: "Settings",
    profile: "Profile",
    logout: "Logout",
    login: "Login",
    login_title: "Welcome to SERVER HUB",
    login_subtitle: "Sign in to manage your server",
    username: "Username",
    password: "Password",
    sign_in: "Sign In",
    signing_in: "Signing in...",
    invalid_credentials: "Invalid username or password",
    system_overview: "System Overview",
    live_monitoring: "Live monitoring and resource usage",
    cpu_usage: "CPU Usage",
    memory: "Memory",
    disk_space: "Disk Space",
    uptime: "Uptime",
    open_ports: "Open Ports",
    top_processes: "Top Processes",
    no_ports: "No open ports detected",
    no_processes: "No processes found",
    kill: "Kill",
    total: "total",
    cores: "Cores",
    load: "Load",
    of: "of",
    explorer: "Explorer",
    new_file: "New File",
    new_folder: "New Folder",
    upload: "Upload",
    search: "Search...",
    name: "Name",
    size: "Size",
    date: "Date",
    rename: "Rename",
    delete: "Delete",
    open: "Open",
    empty_folder: "Empty folder",
    no_results: "No results found",
    drop_to_upload: "Drop files to upload",
    select_file: "Select a file to open",
    save: "Save",
    new_terminal: "New Terminal",
    connected: "Connected",
    connecting: "Connecting",
    reconnecting: "Reconnecting...",
    offline: "Offline",
    clear: "Clear",
    restart: "Restart",
    ai_assistant: "AI Assistant",
    ai_subtitle: "Ask anything about server management, code, or Linux",
    analyze_file: "Analyze File",
    send: "Send",
    thinking: "Thinking...",
    ai_disclaimer: "AI may make mistakes. Verify important commands before running.",
    file_path: "File Path",
    question: "Question",
    analyze: "Analyze",
    analyzing: "Analyzing...",
    admin_panel: "Admin Panel",
    user_management: "User Management",
    create_user: "Create User",
    edit_user: "Edit User",
    delete_user: "Delete User",
    search_users: "Search users...",
    expires_in: "Expires in",
    days: "days",
    no_expiry: "No expiry",
    disabled: "Disabled",
    active: "Active",
    role: "Role",
    display_name: "Display Name",
    cancel: "Cancel",
    save_changes: "Save Changes",
    create: "Create",
    confirm_delete: "Confirm Delete",
    delete_confirm_msg: "Are you sure you want to delete this user?",
    last_login: "Last Login",
    never: "Never",
    settings_title: "Settings",
    telegram_settings: "Telegram Notifications",
    bot_token: "Bot Token",
    chat_id: "Chat ID / Admin ID",
    test_connection: "Test Connection",
    testing: "Testing...",
    enable_telegram: "Enable Telegram Notifications",
    notify_login: "Notify on login",
    notify_register: "Notify on user registration",
    notify_upload: "Notify on file upload",
    notify_error: "Notify on server error",
    language_settings: "Language",
    save_settings: "Save Settings",
    settings_saved: "Settings saved",
    test_success: "Test message sent successfully!",
    test_failed: "Test failed — check token and chat ID",
    profile_title: "Profile",
    change_password: "Change Password",
    current_password: "Current Password",
    new_password: "New Password",
    confirm_password: "Confirm Password",
    upload_avatar: "Upload Avatar",
    account_info: "Account Info",
    subscription: "Subscription",
    expires: "Expires",
    unlimited: "Unlimited",
    save_profile: "Save Profile",
    profile_updated: "Profile updated successfully",
    passwords_dont_match: "Passwords don't match",
    loading: "Loading...",
    error: "Error",
    success: "Success",
    confirm: "Confirm",
    close: "Close",
    back: "Back",
    server_hub: "SERVER HUB",
    activity_log: "Activity Log",
    track_all_actions: "Track all user actions and events",
  },
  ar: {
    dashboard: "لوحة التحكم",
    terminal: "الطرفية",
    editor: "المحرر",
    files: "الملفات",
    ai_chat: "المساعد الذكي",
    commands: "الأوامر",
    admin: "لوحة الإدمن",
    settings: "الإعدادات",
    profile: "الملف الشخصي",
    logout: "تسجيل الخروج",
    login: "تسجيل الدخول",
    login_title: "مرحباً بك في SERVER HUB",
    login_subtitle: "سجّل دخولك لإدارة السيرفر",
    username: "اسم المستخدم",
    password: "كلمة المرور",
    sign_in: "دخول",
    signing_in: "جارٍ الدخول...",
    invalid_credentials: "اسم المستخدم أو كلمة المرور غير صحيحة",
    system_overview: "نظرة عامة على النظام",
    live_monitoring: "مراقبة مباشرة لاستخدام الموارد",
    cpu_usage: "استخدام المعالج",
    memory: "الذاكرة",
    disk_space: "مساحة القرص",
    uptime: "وقت التشغيل",
    open_ports: "المنافذ المفتوحة",
    top_processes: "أبرز العمليات",
    no_ports: "لا توجد منافذ مفتوحة",
    no_processes: "لا توجد عمليات",
    kill: "إيقاف",
    total: "إجمالي",
    cores: "أنوية",
    load: "الحمل",
    of: "من",
    explorer: "المستعرض",
    new_file: "ملف جديد",
    new_folder: "مجلد جديد",
    upload: "رفع ملف",
    search: "بحث...",
    name: "الاسم",
    size: "الحجم",
    date: "التاريخ",
    rename: "إعادة التسمية",
    delete: "حذف",
    open: "فتح",
    empty_folder: "المجلد فارغ",
    no_results: "لا توجد نتائج",
    drop_to_upload: "أسقط الملفات للرفع",
    select_file: "اختر ملفاً للفتح",
    save: "حفظ",
    new_terminal: "طرفية جديدة",
    connected: "متصل",
    connecting: "جارٍ الاتصال",
    reconnecting: "إعادة الاتصال...",
    offline: "غير متصل",
    clear: "مسح",
    restart: "إعادة تشغيل",
    ai_assistant: "المساعد الذكي",
    ai_subtitle: "اسأل عن إدارة السيرفرات أو البرمجة أو لينكس",
    analyze_file: "تحليل ملف",
    send: "إرسال",
    thinking: "جارٍ التفكير...",
    ai_disclaimer: "قد يُخطئ الذكاء الاصطناعي. تحقق من الأوامر المهمة قبل تشغيلها.",
    file_path: "مسار الملف",
    question: "السؤال",
    analyze: "تحليل",
    analyzing: "جارٍ التحليل...",
    admin_panel: "لوحة الإدمن",
    user_management: "إدارة المستخدمين",
    create_user: "إنشاء مستخدم",
    edit_user: "تعديل المستخدم",
    delete_user: "حذف المستخدم",
    search_users: "بحث عن مستخدم...",
    expires_in: "تنتهي خلال",
    days: "أيام",
    no_expiry: "بلا انتهاء",
    disabled: "معطّل",
    active: "نشط",
    role: "الدور",
    display_name: "الاسم الظاهر",
    cancel: "إلغاء",
    save_changes: "حفظ التغييرات",
    create: "إنشاء",
    confirm_delete: "تأكيد الحذف",
    delete_confirm_msg: "هل أنت متأكد من حذف هذا المستخدم؟",
    last_login: "آخر دخول",
    never: "لم يسجّل بعد",
    settings_title: "الإعدادات",
    telegram_settings: "إشعارات تيليجرام",
    bot_token: "توكن البوت",
    chat_id: "معرف المحادثة / الإدمن",
    test_connection: "اختبار الاتصال",
    testing: "جارٍ الاختبار...",
    enable_telegram: "تفعيل إشعارات تيليجرام",
    notify_login: "إشعار عند تسجيل الدخول",
    notify_register: "إشعار عند إنشاء حساب",
    notify_upload: "إشعار عند رفع ملف",
    notify_error: "إشعار عند حدوث خطأ",
    language_settings: "اللغة",
    save_settings: "حفظ الإعدادات",
    settings_saved: "تم حفظ الإعدادات",
    test_success: "تم إرسال رسالة اختبار بنجاح!",
    test_failed: "فشل الاختبار — تحقق من التوكن ومعرف المحادثة",
    profile_title: "الملف الشخصي",
    change_password: "تغيير كلمة المرور",
    current_password: "كلمة المرور الحالية",
    new_password: "كلمة المرور الجديدة",
    confirm_password: "تأكيد كلمة المرور",
    upload_avatar: "رفع صورة شخصية",
    account_info: "معلومات الحساب",
    subscription: "الاشتراك",
    expires: "ينتهي في",
    unlimited: "غير محدود",
    save_profile: "حفظ الملف",
    profile_updated: "تم تحديث الملف الشخصي",
    passwords_dont_match: "كلمتا المرور غير متطابقتين",
    loading: "جارٍ التحميل...",
    error: "خطأ",
    success: "نجاح",
    confirm: "تأكيد",
    close: "إغلاق",
    back: "رجوع",
    server_hub: "سيرفر هاب",
    activity_log: "سجل النشاط",
    track_all_actions: "تتبع جميع إجراءات المستخدمين والأحداث",
  },
} as const;

type TranslationKey = keyof typeof translations.en;

interface LangContextValue {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: TranslationKey) => string;
  isRTL: boolean;
}

const LangContext = createContext<LangContextValue | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    return (localStorage.getItem("sh_lang") as Lang) || "en";
  });

  useEffect(() => {
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = lang;
  }, [lang]);

  const setLang = (l: Lang) => {
    setLangState(l);
    localStorage.setItem("sh_lang", l);
  };

  const t = (key: TranslationKey): string => {
    return translations[lang][key] || translations.en[key] || key;
  };

  return (
    <LangContext.Provider value={{ lang, setLang, t, isRTL: lang === "ar" }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error("useLang must be used inside LanguageProvider");
  return ctx;
}
